export var EMOJI_MAP = {
  // Smileys & Emotion
  'grinning': '😀', 'smiley': '😃', 'smile': '😄', 'grin': '😁',
  'laughing': '😆', 'satisfied': '😆', 'sweat_smile': '😅',
  'rofl': '🤣', 'rolling_on_the_floor_laughing': '🤣',
  'joy': '😂', 'face_with_tears_of_joy': '😂',
  'slightly_smiling_face': '🙂', 'upside_down_face': '🙃',
  'melting_face': '🫠', 'wink': '😉', 'blush': '😊',
  'innocent': '😇', 'smiling_face_with_three_hearts': '🥰',
  'heart_eyes': '😍', 'star_struck': '🤩', 'kissing_heart': '😘',
  'kissing': '😗', 'relaxed': '☺️', 'kissing_closed_eyes': '😚',
  'kissing_smiling_eyes': '😙', 'smiling_face_with_tear': '🥲',
  'yum': '😋', 'stuck_out_tongue': '😛',
  'stuck_out_tongue_winking_eye': '😜', 'zany_face': '🤪',
  'stuck_out_tongue_closed_eyes': '😝', 'money_mouth_face': '🤑',
  'hugs': '🤗', 'hugging_face': '🤗',
  'hand_over_mouth': '🤭', 'shushing_face': '🤫',
  'thinking_face': '🤔', 'thinking': '🤔',
  'saluting_face': '🫡', 'zipper_mouth_face': '🤐',
  'raised_eyebrow': '🤨', 'neutral_face': '😐',
  'expressionless': '😑', 'no_mouth': '😶',
  'dotted_line_face': '🫥', 'face_in_clouds': '😶‍🌫️',
  'smirk': '😏', 'unamused': '😒', 'rolling_eyes': '🙄',
  'grimacing': '😬', 'face_exhaling': '😮‍💨', 'lying_face': '🤥',
  'shaking_face': '🫨',
  'relieved': '😌', 'pensive': '😔', 'sleepy': '😪',
  'drooling_face': '🤤', 'sleeping': '😴',
  'mask': '😷', 'face_with_thermometer': '🤒',
  'face_with_head_bandage': '🤕', 'nauseated_face': '🤢',
  'face_vomiting': '🤮', 'sneezing_face': '🤧',
  'hot_face': '🥵', 'cold_face': '🥶', 'woozy_face': '🥴',
  'dizzy_face': '😵', 'face_with_spiral_eyes': '😵‍💫',
  'exploding_head': '🤯',
  'cowboy_hat_face': '🤠', 'partying_face': '🥳',
  'disguised_face': '🥸',
  'sunglasses': '😎', 'nerd_face': '🤓', 'face_with_monocle': '🧐',
  'confused': '😕', 'worried': '😟', 'slightly_frowning_face': '🙁',
  'frowning_face': '☹️', 'open_mouth': '😮', 'hushed': '😯',
  'astonished': '😲', 'flushed': '😳', 'pleading_face': '🥺',
  'face_holding_back_tears': '🥹',
  'frowning': '😦', 'anguished': '😧', 'fearful': '😨',
  'cold_sweat': '😰', 'disappointed_relieved': '😥',
  'cry': '😢', 'sob': '😭', 'scream': '😱',
  'confounded': '😖', 'persevere': '😣', 'disappointed': '😞',
  'sweat': '😓', 'weary': '😩', 'tired_face': '😫',
  'yawning_face': '🥱',
  'triumph': '😤', 'rage': '😡', 'pout': '😡',
  'angry': '😠', 'face_with_symbols_on_mouth': '🤬', 'cursing_face': '🤬',
  'smiling_imp': '😈', 'imp': '👿',
  'skull': '💀', 'skull_and_crossbones': '☠️',
  'hankey': '💩', 'poop': '💩', 'shit': '💩',
  'clown_face': '🤡', 'japanese_ogre': '👹', 'japanese_goblin': '👺',
  'ghost': '👻', 'alien': '👽', 'space_invader': '👾',
  'robot_face': '🤖', 'robot': '🤖',
  'smiley_cat': '😺', 'smile_cat': '😸', 'joy_cat': '😹',
  'heart_eyes_cat': '😻', 'smirk_cat': '😼', 'kissing_cat': '😽',
  'scream_cat': '🙀', 'crying_cat_face': '😿', 'pouting_cat': '😾',
  'see_no_evil': '🙈', 'hear_no_evil': '🙉', 'speak_no_evil': '🙊',

  // Hearts
  'heart': '❤️', 'red_heart': '❤️', 'hearts': '❤️',
  'heartpulse': '💗', 'heartbeat': '💓',
  'revolving_hearts': '💞', 'two_hearts': '💕',
  'sparkling_heart': '💖', 'cupid': '💘',
  'gift_heart': '💝', 'heart_decoration': '💟',
  'broken_heart': '💔', 'heart_on_fire': '❤️‍🔥',
  'mending_heart': '❤️‍🩹',
  'orange_heart': '🧡', 'yellow_heart': '💛', 'green_heart': '💚',
  'blue_heart': '💙', 'purple_heart': '💜', 'brown_heart': '🤎',
  'black_heart': '🖤', 'white_heart': '🤍', 'pink_heart': '🩷',
  'light_blue_heart': '🩵', 'grey_heart': '🩶',
  'growing_heart': '💗', 'love_letter': '💌',

  // Emotion
  'kiss': '💋', 'hundred': '💯', '100': '💯',
  'anger': '💢', 'boom': '💥', 'collision': '💥',
  'sweat_drops': '💦', 'dash': '💨', 'hole': '🕳️',
  'speech_balloon': '💬', 'thought_balloon': '💭',
  'zzz': '💤', 'wave_dash': '〰️',

  // Hands & Gestures
  'wave': '👋', 'raised_back_of_hand': '🤚',
  'raised_hand_with_fingers_splayed': '🖐️', 'hand': '✋', 'raised_hand': '✋',
  'vulcan_salute': '🖖', 'rightwards_hand': '🫱', 'leftwards_hand': '🫲',
  'palm_down_hand': '🫳', 'palm_up_hand': '🫴',
  'ok_hand': '👌', 'pinched_fingers': '🤌',
  'pinching_hand': '🤏', 'v': '✌️', 'peace': '✌️',
  'crossed_fingers': '🤞', 'hand_with_index_finger_and_thumb_crossed': '🫰',
  'love_you_gesture': '🤟', 'the_horns': '🤘', 'metal': '🤘',
  'call_me_hand': '🤙',
  'point_left': '👈', 'point_right': '👉',
  'point_up_2': '👆', 'point_down': '👇',
  'point_up': '☝️', 'index_pointing_at_the_viewer': '🫵',
  '+1': '👍', 'thumbsup': '👍', '-1': '👎', 'thumbsdown': '👎',
  'fist': '✊', 'fist_raised': '✊',
  'facepunch': '👊', 'punch': '👊', 'fist_oncoming': '👊',
  'fist_left': '🤛', 'fist_right': '🤜',
  'clap': '👏', 'raised_hands': '🙌', 'heart_hands': '🫶',
  'open_hands': '👐', 'palms_up_together': '🤲',
  'handshake': '🤝', 'pray': '🙏',
  'writing_hand': '✍️', 'nail_care': '💅', 'selfie': '🤳',
  'muscle': '💪', 'mechanical_arm': '🦾', 'mechanical_leg': '🦿',
  'leg': '🦵', 'foot': '🦶',

  // People
  'baby': '👶', 'child': '🧒', 'boy': '👦', 'girl': '👧',
  'adult': '🧑', 'man': '👨', 'woman': '👩',
  'older_adult': '🧓', 'older_man': '👴', 'older_woman': '👵',
  'person_frowning': '🙍', 'person_pouting': '🙎',
  'no_good': '🙅', 'ok_woman': '🙆', 'ok_person': '🙆',
  'raising_hand': '🙋', 'bow': '🙇', 'facepalm': '🤦',
  'shrug': '🤷', 'person_shrugging': '🤷',
  'cop': '👮', 'detective': '🕵️',
  'construction_worker': '👷', 'guard': '💂',
  'ninja': '🥷', 'mx_claus': '🧑‍🎄',
  'princess': '👸', 'prince': '🤴',
  'superhero': '🦸', 'supervillain': '🦹',
  'mage': '🧙', 'fairy': '🧚', 'vampire': '🧛',
  'merperson': '🧜', 'elf': '🧝', 'genie': '🧞', 'zombie': '🧟',
  'troll': '🧌',
  'person_in_tuxedo': '🤵', 'bride_with_veil': '👰',
  'pregnant_woman': '🤰', 'pregnant_person': '🫄',
  'breast_feeding': '🤱',
  'angel': '👼', 'santa': '🎅', 'mrs_claus': '🤶',
  'dancer': '💃', 'man_dancing': '🕺',
  'person_in_steamy_room': '🧖',
  'person_climbing': '🧗', 'person_fencing': '🤺',
  'horse_racing': '🏇', 'skier': '⛷️', 'snowboarder': '🏂',
  'person_golfing': '🏌️', 'surfer': '🏄',
  'rowboat': '🚣', 'swimmer': '🏊',
  'person_bouncing_ball': '⛹️', 'weight_lifter': '🏋️',
  'bicyclist': '🚴', 'mountain_bicyclist': '🚵',
  'person_doing_cartwheel': '🤸', 'wrestlers': '🤼',
  'water_polo': '🤽', 'person_playing_handball': '🤾',
  'juggling': '🤹', 'person_in_lotus_position': '🧘',
  'bath': '🛀', 'person_in_bed': '🛌',
  'people_holding_hands': '🧑‍🤝‍🧑',
  'couple': '👫', 'two_men_holding_hands': '👬',
  'two_women_holding_hands': '👭',
  'couplekiss': '💏', 'couple_with_heart': '💑',
  'family': '👪',
  'bust_in_silhouette': '👤', 'busts_in_silhouette': '👥',
  'footprints': '👣',

  // Body parts
  'brain': '🧠', 'anatomical_heart': '🫀', 'lungs': '🫁',
  'bone': '🦴', 'tooth': '🦷', 'tongue': '👅',
  'ear': '👂', 'nose': '👃', 'eye': '👁️', 'eyes': '👀',
  'lips': '👄', 'biting_lip': '🫦',

  // Animals
  'dog': '🐶', 'dog2': '🐕', 'guide_dog': '🦮', 'service_dog': '🐕‍🦺',
  'poodle': '🐩', 'wolf': '🐺', 'fox_face': '🦊', 'raccoon': '🦝',
  'cat': '🐱', 'cat2': '🐈', 'black_cat': '🐈‍⬛',
  'lion_face': '🦁', 'lion': '🦁',
  'tiger': '🐯', 'tiger2': '🐅', 'leopard': '🐆',
  'horse': '🐴', 'racehorse': '🐎', 'unicorn': '🦄', 'unicorn_face': '🦄',
  'zebra_face': '🦓', 'deer': '🦌', 'bison': '🦬',
  'cow': '🐮', 'ox': '🐂', 'water_buffalo': '🐃', 'cow2': '🐄',
  'pig': '🐷', 'pig2': '🐖', 'boar': '🐗', 'pig_nose': '🐽',
  'ram': '🐏', 'sheep': '🐑', 'goat': '🐐', 'dromedary_camel': '🐪',
  'camel': '🐫', 'llama': '🦙', 'giraffe_face': '🦒',
  'elephant': '🐘', 'mammoth': '🦣', 'rhinoceros': '🦏', 'hippopotamus': '🦛',
  'mouse': '🐭', 'mouse2': '🐁', 'rat': '🐀', 'hamster': '🐹',
  'rabbit': '🐰', 'rabbit2': '🐇', 'chipmunk': '🐿️',
  'beaver': '🦫', 'hedgehog': '🦔',
  'bat': '🦇', 'bear': '🐻', 'polar_bear': '🐻‍❄️',
  'koala': '🐨', 'panda_face': '🐼', 'sloth': '🦥',
  'otter': '🦦', 'skunk': '🦨', 'kangaroo': '🦘',
  'badger': '🦡', 'feet': '🐾', 'paw_prints': '🐾',
  'turkey': '🦃', 'chicken': '🐔', 'rooster': '🐓',
  'hatching_chick': '🐣', 'baby_chick': '🐤', 'hatched_chick': '🐥',
  'bird': '🐦', 'penguin': '🐧', 'dove_of_peace': '🕊️', 'dove': '🕊️',
  'eagle': '🦅', 'duck': '🦆', 'swan': '🦢', 'owl': '🦉',
  'dodo': '🦤', 'feather': '🪶', 'flamingo': '🦩', 'peacock': '🦚',
  'parrot': '🦜', 'goose': '🪿',
  'frog': '🐸', 'crocodile': '🐊', 'turtle': '🐢',
  'lizard': '🦎', 'snake': '🐍', 'dragon_face': '🐲', 'dragon': '🐉',
  'sauropod': '🦕', 't_rex': '🦖',
  'whale': '🐳', 'whale2': '🐋', 'dolphin': '🐬', 'flipper': '🐬',
  'seal': '🦭', 'fish': '🐟', 'tropical_fish': '🐠', 'blowfish': '🐡',
  'shark': '🦈', 'octopus': '🐙', 'shell': '🐚', 'coral': '🪸',
  'jellyfish': '🪼',
  'snail': '🐌', 'butterfly': '🦋', 'bug': '🐛', 'ant': '🐜',
  'bee': '🐝', 'honeybee': '🐝', 'beetle': '🪲', 'ladybug': '🐞',
  'lady_beetle': '🐞', 'cricket': '🦗', 'cockroach': '🪳',
  'spider': '🕷️', 'spider_web': '🕸️', 'scorpion': '🦂',
  'mosquito': '🦟', 'fly': '🪰', 'worm': '🪱', 'microbe': '🦠',

  // Plants & Nature
  'bouquet': '💐', 'cherry_blossom': '🌸', 'white_flower': '💮',
  'lotus': '🪷', 'rosette': '🏵️', 'rose': '🌹', 'wilted_flower': '🥀',
  'hibiscus': '🌺', 'sunflower': '🌻', 'blossom': '🌼', 'tulip': '🌷',
  'hyacinth': '🪻',
  'seedling': '🌱', 'potted_plant': '🪴',
  'evergreen_tree': '🌲', 'deciduous_tree': '🌳', 'palm_tree': '🌴',
  'cactus': '🌵', 'ear_of_rice': '🌾', 'herb': '🌿',
  'shamrock': '☘️', 'four_leaf_clover': '🍀',
  'maple_leaf': '🍁', 'fallen_leaf': '🍂', 'leaves': '🍃',
  'empty_nest': '🪹', 'nest_with_eggs': '🪺',
  'mushroom': '🍄',

  // Food & Drink
  'grapes': '🍇', 'melon': '🍈', 'watermelon': '🍉', 'tangerine': '🍊',
  'orange': '🍊', 'mandarin': '🍊', 'lemon': '🍋', 'banana': '🍌',
  'pineapple': '🍍', 'mango': '🥭', 'apple': '🍎', 'green_apple': '🍏',
  'pear': '🍐', 'peach': '🍑', 'cherries': '🍒', 'strawberry': '🍓',
  'blueberries': '🫐', 'kiwi_fruit': '🥝', 'tomato': '🍅',
  'olive': '🫒', 'coconut': '🥥',
  'avocado': '🥑', 'eggplant': '🍆', 'potato': '🥔', 'carrot': '🥕',
  'corn': '🌽', 'hot_pepper': '🌶️', 'bell_pepper': '🫑',
  'cucumber': '🥒', 'leafy_green': '🥬', 'broccoli': '🥦',
  'garlic': '🧄', 'onion': '🧅', 'peanuts': '🥜', 'beans': '🫘',
  'chestnut': '🌰', 'ginger_root': '🫚', 'pea_pod': '🫛',
  'bread': '🍞', 'croissant': '🥐', 'baguette_bread': '🥖',
  'flatbread': '🫓', 'pretzel': '🥨', 'bagel': '🥯',
  'pancakes': '🥞', 'waffle': '🧇',
  'cheese_wedge': '🧀', 'cheese': '🧀',
  'meat_on_bone': '🍖', 'poultry_leg': '🍗', 'cut_of_meat': '🥩',
  'bacon': '🥓', 'hamburger': '🍔', 'fries': '🍟',
  'pizza': '🍕', 'hotdog': '🌭', 'sandwich': '🥪',
  'taco': '🌮', 'burrito': '🌯', 'tamale': '🫔',
  'stuffed_flatbread': '🥙', 'falafel': '🧆',
  'egg': '🥚', 'cooking': '🍳', 'fried_egg': '🍳',
  'shallow_pan_of_food': '🥘', 'stew': '🍲', 'fondue': '🫕',
  'bowl_with_spoon': '🥣', 'green_salad': '🥗', 'popcorn': '🍿',
  'butter': '🧈', 'salt': '🧂', 'canned_food': '🥫',
  'bento': '🍱', 'rice_cracker': '🍘', 'rice_ball': '🍙',
  'rice': '🍚', 'curry': '🍛', 'ramen': '🍜', 'noodles': '🍜',
  'spaghetti': '🍝', 'sweet_potato': '🍠',
  'oden': '🍢', 'sushi': '🍣', 'fried_shrimp': '🍤',
  'fish_cake': '🍥', 'moon_cake': '🥮', 'dango': '🍡',
  'dumpling': '🥟', 'fortune_cookie': '🥠', 'takeout_box': '🥡',
  'oyster': '🦪', 'lobster': '🦞', 'shrimp': '🦐', 'squid': '🦑',
  'crab': '🦀',
  'icecream': '🍦', 'shaved_ice': '🍧', 'ice_cream': '🍨',
  'doughnut': '🍩', 'donut': '🍩', 'cookie': '🍪',
  'birthday': '🎂', 'cake': '🍰', 'shortcake': '🍰',
  'cupcake': '🧁', 'pie': '🥧',
  'chocolate_bar': '🍫', 'candy': '🍬', 'lollipop': '🍭',
  'custard': '🍮', 'honey_pot': '🍯',
  'baby_bottle': '🍼', 'glass_of_milk': '🥛', 'milk_glass': '🥛',
  'coffee': '☕', 'teapot': '🫖', 'tea': '🍵',
  'sake': '🍶', 'champagne': '🍾', 'wine_glass': '🍷',
  'cocktail': '🍸', 'tropical_drink': '🍹', 'beer': '🍺',
  'beers': '🍻', 'clinking_glasses': '🥂', 'tumbler_glass': '🥃',
  'pouring_liquid': '🫗',
  'cup_with_straw': '🥤', 'bubble_tea': '🧋',
  'beverage_box': '🧃', 'mate_drink': '🧉', 'ice_cube': '🧊',
  'chopsticks': '🥢', 'fork_and_knife': '🍴',
  'spoon': '🥄', 'knife': '🔪', 'hocho': '🔪',
  'plate_with_cutlery': '🍽️', 'jar': '🫙',

  // Travel & Places
  'earth_africa': '🌍', 'earth_americas': '🌎', 'earth_asia': '🌏',
  'globe_with_meridians': '🌐', 'world_map': '🗺️',
  'compass': '🧭',
  'mountain_snow': '🏔️', 'mountain': '⛰️', 'volcano': '🌋',
  'mount_fuji': '🗻', 'camping': '🏕️', 'beach_with_umbrella': '🏖️',
  'desert': '🏜️', 'desert_island': '🏝️', 'national_park': '🏞️',
  'stadium': '🏟️', 'classical_building': '🏛️',
  'building_construction': '🏗️', 'bricks': '🧱',
  'rock': '🪨', 'wood': '🪵',
  'hut': '🛖', 'houses': '🏘️', 'derelict_house': '🏚️',
  'house': '🏠', 'house_with_garden': '🏡',
  'office': '🏢', 'post_office': '🏣', 'european_post_office': '🏤',
  'hospital': '🏥', 'bank': '🏦', 'hotel': '🏨',
  'love_hotel': '🏩', 'convenience_store': '🏪',
  'school': '🏫', 'department_store': '🏬',
  'factory': '🏭', 'japanese_castle': '🏯', 'european_castle': '🏰',
  'wedding': '💒', 'tokyo_tower': '🗼', 'statue_of_liberty': '🗽',
  'church': '⛪', 'mosque': '🕌', 'hindu_temple': '🛕',
  'synagogue': '🕍', 'shinto_shrine': '⛩️', 'kaaba': '🕋',
  'fountain': '⛲', 'tent': '⛺', 'foggy': '🌁',
  'night_with_stars': '🌃', 'cityscape': '🏙️',
  'sunrise_over_mountains': '🌄', 'sunrise': '🌅',
  'city_sunset': '🌆', 'city_sunrise': '🌇',
  'bridge_at_night': '🌉', 'hotsprings': '♨️',
  'carousel_horse': '🎠', 'playground_slide': '🛝',
  'ferris_wheel': '🎡', 'roller_coaster': '🎢',
  'barber': '💈', 'circus_tent': '🎪',
  'steam_locomotive': '🚂', 'railway_car': '🚃',
  'bullettrain_side': '🚄', 'bullettrain_front': '🚅',
  'train2': '🚆', 'metro': '🚇', 'light_rail': '🚈',
  'station': '🚉', 'tram': '🚊', 'monorail': '🚝',
  'mountain_railway': '🚞', 'train': '🚋',
  'bus': '🚌', 'oncoming_bus': '🚍', 'trolleybus': '🚎',
  'minibus': '🚐', 'ambulance': '🚑', 'fire_engine': '🚒',
  'police_car': '🚓', 'oncoming_police_car': '🚔',
  'taxi': '🚕', 'oncoming_taxi': '🚖',
  'car': '🚗', 'red_car': '🚗', 'oncoming_automobile': '🚘',
  'blue_car': '🚙', 'pickup_truck': '🛻',
  'truck': '🚚', 'articulated_lorry': '🚛',
  'tractor': '🚜', 'racing_car': '🏎️', 'motorcycle': '🏍️',
  'motor_scooter': '🛵', 'manual_wheelchair': '🦽',
  'motorized_wheelchair': '🦼', 'auto_rickshaw': '🛺',
  'bike': '🚲', 'kick_scooter': '🛴', 'skateboard': '🛹',
  'roller_skate': '🛼',
  'busstop': '🚏', 'motorway': '🛣️', 'railway_track': '🛤️',
  'oil_drum': '🛢️', 'fuelpump': '⛽',
  'wheel': '🛞', 'rotating_light': '🚨',
  'traffic_light': '🚥', 'vertical_traffic_light': '🚦',
  'stop_sign': '🛑', 'construction': '🚧',
  'anchor': '⚓', 'ring_buoy': '🛟',
  'boat': '⛵', 'sailboat': '⛵', 'canoe': '🛶',
  'speedboat': '🚤', 'passenger_ship': '🛳️',
  'ferry': '⛴️', 'motor_boat': '🛥️', 'ship': '🚢',
  'airplane': '✈️', 'small_airplane': '🛩️',
  'flight_departure': '🛫', 'flight_arrival': '🛬',
  'parachute': '🪂', 'seat': '💺',
  'helicopter': '🚁', 'suspension_railway': '🚟',
  'mountain_cableway': '🚠', 'aerial_tramway': '🚡',
  'artificial_satellite': '🛰️', 'rocket': '🚀',
  'flying_saucer': '🛸',
  'bellhop_bell': '🛎️', 'luggage': '🧳',

  // Time
  'hourglass': '⌛', 'hourglass_flowing_sand': '⏳',
  'watch': '⌚', 'alarm_clock': '⏰',
  'stopwatch': '⏱️', 'timer_clock': '⏲️',
  'mantelpiece_clock': '🕰️',
  'clock12': '🕛', 'clock1': '🕐', 'clock2': '🕑', 'clock3': '🕒',
  'clock4': '🕓', 'clock5': '🕔', 'clock6': '🕕', 'clock7': '🕖',
  'clock8': '🕗', 'clock9': '🕘', 'clock10': '🕙', 'clock11': '🕚',

  // Weather & Sky
  'new_moon': '🌑', 'waxing_crescent_moon': '🌒',
  'first_quarter_moon': '🌓', 'moon': '🌔', 'waxing_gibbous_moon': '🌔',
  'full_moon': '🌕', 'waning_gibbous_moon': '🌖',
  'last_quarter_moon': '🌗', 'waning_crescent_moon': '🌘',
  'crescent_moon': '🌙', 'new_moon_with_face': '🌚',
  'first_quarter_moon_with_face': '🌛', 'last_quarter_moon_with_face': '🌜',
  'thermometer': '🌡️', 'sunny': '☀️', 'sun_with_face': '🌞',
  'ringed_planet': '🪐',
  'star': '⭐', 'star2': '🌟', 'stars': '🌠',
  'milky_way': '🌌', 'cloud': '☁️',
  'partly_sunny': '⛅', 'sun_behind_large_cloud': '🌥️',
  'sun_behind_small_cloud': '🌤️', 'sun_behind_rain_cloud': '🌦️',
  'cloud_with_rain': '🌧️', 'cloud_with_snow': '🌨️',
  'cloud_with_lightning': '🌩️', 'cloud_with_lightning_and_rain': '⛈️',
  'snowflake': '❄️', 'snowman': '☃️', 'snowman_without_snow': '⛄',
  'comet': '☄️', 'fire': '🔥',
  'droplet': '💧', 'ocean': '🌊',
  'rainbow': '🌈', 'sparkles': '✨', 'sparkle': '❇️',
  'umbrella': '☂️', 'umbrella_with_rain_drops': '☔',
  'zap': '⚡', 'lightning': '⚡',
  'tornado': '🌪️', 'fog': '🌫️', 'wind_blowing_face': '🌬️',

  // Events & Activities
  'jack_o_lantern': '🎃', 'christmas_tree': '🎄',
  'fireworks': '🎆', 'sparkler': '🎇',
  'firecracker': '🧨', 'tada': '🎉', 'party_popper': '🎉',
  'confetti_ball': '🎊', 'tanabata_tree': '🎋',
  'bamboo': '🎍', 'dolls': '🎎', 'flags': '🎏',
  'wind_chime': '🎐', 'rice_scene': '🎑',
  'red_envelope': '🧧', 'ribbon': '🎀', 'gift': '🎁',
  'reminder_ribbon': '🎗️', 'tickets': '🎟️', 'ticket': '🎫',
  'military_medal': '🎖️', 'trophy': '🏆',
  'sports_medal': '🏅', 'medal': '🏅',
  'first_place_medal': '🥇', 'second_place_medal': '🥈',
  'third_place_medal': '🥉',
  'soccer': '⚽', 'baseball': '⚾', 'softball': '🥎',
  'basketball': '🏀', 'volleyball': '🏐',
  'football': '🏈', 'rugby_football': '🏉',
  'tennis': '🎾', 'flying_disc': '🥏',
  'bowling': '🎳', 'cricket_game': '🏏',
  'field_hockey': '🏑', 'ice_hockey': '🏒',
  'lacrosse': '🥍', 'ping_pong': '🏓', 'table_tennis': '🏓',
  'badminton': '🏸', 'boxing_glove': '🥊',
  'martial_arts_uniform': '🥋', 'goal_net': '🥅',
  'golf': '⛳', 'ice_skate': '⛸️', 'fishing_pole_and_fish': '🎣',
  'diving_mask': '🤿', 'running_shirt_with_sash': '🎽',
  'ski': '🎿', 'sled': '🛷', 'curling_stone': '🥌',
  'dart': '🎯', 'direct_hit': '🎯',
  'yo_yo': '🪀', 'kite': '🪁', 'water_pistol': '🔫',
  'billiards': '🎱', '8ball': '🎱',
  'crystal_ball': '🔮', 'magic_wand': '🪄',
  'video_game': '🎮', 'joystick': '🕹️',
  'slot_machine': '🎰', 'game_die': '🎲',
  'jigsaw': '🧩', 'teddy_bear': '🧸',
  'pinata': '🪅', 'mirror_ball': '🪩', 'nesting_dolls': '🪆',
  'spades': '♠️', 'hearts_suit': '♥️', 'diamonds': '♦️', 'clubs': '♣️',
  'chess_pawn': '♟️', 'black_joker': '🃏', 'mahjong': '🀄',
  'flower_playing_cards': '🎴',
  'performing_arts': '🎭', 'framed_picture': '🖼️',
  'art': '🎨', 'palette': '🎨', 'thread': '🧵', 'sewing_needle': '🪡',
  'yarn': '🧶', 'knot': '🪢',

  // Music
  'musical_note': '🎵', 'notes': '🎶', 'musical_score': '🎼',
  'studio_microphone': '🎙️', 'level_slider': '🎚️',
  'control_knobs': '🎛️', 'microphone': '🎤',
  'headphones': '🎧', 'radio': '📻',
  'saxophone': '🎷', 'accordion': '🪗',
  'guitar': '🎸', 'musical_keyboard': '🎹',
  'trumpet': '🎺', 'violin': '🎻',
  'banjo': '🪕', 'drum_with_drumsticks': '🥁', 'drum': '🥁',
  'long_drum': '🪘', 'maracas': '🪇', 'flute': '🪈',

  // Objects
  'glasses': '👓', 'dark_sunglasses': '🕶️',
  'goggles': '🥽', 'lab_coat': '🥼', 'safety_vest': '🦺',
  'necktie': '👔', 'shirt': '👕', 'tshirt': '👕',
  'jeans': '👖', 'scarf': '🧣', 'gloves': '🧤',
  'coat': '🧥', 'socks': '🧦', 'dress': '👗',
  'kimono': '👘', 'sari': '🥻', 'one_piece_swimsuit': '🩱',
  'swim_brief': '🩲', 'shorts': '🩳',
  'bikini': '👙', 'womans_clothes': '👚',
  'folding_hand_fan': '🪭', 'purse': '👛',
  'handbag': '👜', 'pouch': '👝',
  'shopping': '🛍️', 'shopping_bags': '🛍️',
  'school_satchel': '🎒', 'backpack': '🎒',
  'thong_sandal': '🩴',
  'mans_shoe': '👞', 'shoe': '👞',
  'athletic_shoe': '👟', 'hiking_boot': '🥾',
  'flat_shoe': '🥿', 'high_heel': '👠',
  'sandal': '👡', 'ballet_shoes': '🩰',
  'boot': '👢', 'hair_pick': '🪮',
  'crown': '👑', 'womans_hat': '👒',
  'tophat': '🎩', 'mortar_board': '🎓',
  'billed_cap': '🧢', 'military_helmet': '🪖',
  'rescue_worker_helmet': '⛑️',
  'prayer_beads': '📿', 'lipstick': '💄',
  'ring': '💍', 'gem': '💎',

  // Sound & Communication
  'mute': '🔇', 'speaker': '🔈', 'sound': '🔉', 'loud_sound': '🔊',
  'loudspeaker': '📢', 'mega': '📣',
  'postal_horn': '📯', 'bell': '🔔', 'no_bell': '🔕',

  // Tech & Electronics
  'computer': '💻', 'desktop_computer': '🖥️',
  'printer': '🖨️', 'keyboard': '⌨️',
  'computer_mouse': '🖱️', 'trackball': '🖲️',
  'minidisc': '💽', 'floppy_disk': '💾',
  'cd': '💿', 'dvd': '📀',
  'abacus': '🧮',
  'movie_camera': '🎥', 'film_strip': '🎞️',
  'film_projector': '📽️', 'clapper': '🎬',
  'tv': '📺', 'camera': '📷', 'camera_flash': '📸',
  'video_camera': '📹', 'vhs': '📼',
  'mag': '🔍', 'mag_right': '🔎',
  'candle': '🕯️', 'bulb': '💡', 'flashlight': '🔦',
  'izakaya_lantern': '🏮', 'lantern': '🏮',
  'diya_lamp': '🪔',
  'iphone': '📱', 'calling': '📲',
  'phone': '☎️', 'telephone': '☎️', 'telephone_receiver': '📞',
  'pager': '📟', 'fax': '📠',
  'battery': '🔋', 'low_battery': '🪫',
  'electric_plug': '🔌', 'satellite': '📡',

  // Office & Writing
  'notebook_with_decorative_cover': '📔', 'closed_book': '📕',
  'open_book': '📖', 'book': '📖', 'green_book': '📗',
  'blue_book': '📘', 'orange_book': '📙',
  'books': '📚', 'notebook': '📓',
  'ledger': '📒', 'page_with_curl': '📃',
  'scroll': '📜', 'page_facing_up': '📄',
  'newspaper': '📰', 'rolled_up_newspaper': '🗞️',
  'bookmark_tabs': '📑', 'bookmark': '🔖', 'label': '🏷️',
  'money_with_wings': '💸', 'dollar': '💵',
  'yen': '💴', 'euro': '💶', 'pound': '💷',
  'coin': '🪙', 'moneybag': '💰',
  'credit_card': '💳', 'receipt': '🧾',
  'chart': '💹',
  'envelope': '✉️', 'email': '📧', 'e_mail': '📧',
  'incoming_envelope': '📨', 'envelope_with_arrow': '📩',
  'outbox_tray': '📤', 'inbox_tray': '📥',
  'package': '📦', 'mailbox': '📫',
  'mailbox_closed': '📪', 'mailbox_with_mail': '📬',
  'mailbox_with_no_mail': '📭', 'postbox': '📮',
  'ballot_box': '🗳️',
  'pencil2': '✏️', 'pencil': '✏️',
  'black_nib': '✒️', 'fountain_pen': '🖋️',
  'pen': '🖊️', 'paintbrush': '🖌️', 'crayon': '🖍️',
  'memo': '📝', 'writing': '📝',
  'briefcase': '💼', 'file_folder': '📁',
  'open_file_folder': '📂', 'card_index_dividers': '🗂️',
  'calendar': '📅', 'date': '📅',
  'torn_off_calendar': '📆', 'spiral_notepad': '🗒️',
  'spiral_calendar': '🗓️',
  'card_index': '📇', 'chart_with_upwards_trend': '📈',
  'chart_with_downwards_trend': '📉',
  'bar_chart': '📊',
  'clipboard': '📋', 'pushpin': '📌', 'round_pushpin': '📍',
  'paperclip': '📎', 'paperclips': '🖇️',
  'straight_ruler': '📏', 'triangular_ruler': '📐',
  'scissors': '✂️', 'card_file_box': '🗃️',
  'file_cabinet': '🗄️', 'wastebasket': '🗑️',

  // Lock & Key
  'lock': '🔒', 'unlock': '🔓',
  'lock_with_ink_pen': '🔏', 'closed_lock_with_key': '🔐',
  'key': '🔑', 'old_key': '🗝️',

  // Tools
  'hammer': '🔨', 'axe': '🪓', 'pick': '⛏️',
  'hammer_and_pick': '⚒️', 'hammer_and_wrench': '🛠️',
  'dagger': '🗡️', 'crossed_swords': '⚔️',
  'bomb': '💣', 'boomerang': '🪃',
  'bow_and_arrow': '🏹', 'shield': '🛡️',
  'carpentry_saw': '🪚', 'wrench': '🔧',
  'screwdriver': '🪛', 'nut_and_bolt': '🔩',
  'gear': '⚙️', 'clamp': '🗜️',
  'balance_scale': '⚖️', 'probing_cane': '🦯',
  'link': '🔗', 'chains': '⛓️', 'hook': '🪝',
  'toolbox': '🧰', 'magnet': '🧲', 'ladder': '🪜',

  // Science & Medical
  'alembic': '⚗️', 'test_tube': '🧪', 'petri_dish': '🧫',
  'dna': '🧬', 'microscope': '🔬', 'telescope': '🔭',
  'pill': '💊', 'syringe': '💉',
  'drop_of_blood': '🩸', 'stethoscope': '🩺',
  'x_ray': '🩻', 'adhesive_bandage': '🩹', 'bandage': '🩹',
  'crutch': '🩼',

  // Household
  'door': '🚪', 'elevator': '🛗',
  'mirror': '🪞', 'window': '🪟',
  'bed': '🛏️', 'couch_and_lamp': '🛋️',
  'chair': '🪑', 'toilet': '🚽', 'plunger': '🪠',
  'shower': '🚿', 'bathtub': '🛁',
  'mouse_trap': '🪤', 'razor': '🪒',
  'lotion_bottle': '🧴', 'safety_pin': '🧷',
  'broom': '🧹', 'basket': '🧺',
  'roll_of_paper': '🧻', 'bucket': '🪣',
  'soap': '🧼', 'bubbles': '🫧',
  'toothbrush': '🪥', 'sponge': '🧽',
  'fire_extinguisher': '🧯',
  'shopping_cart': '🛒',

  // Symbols & Signs
  'smoking': '🚬', 'coffin': '⚰️', 'headstone': '🪦',
  'funeral_urn': '⚱️', 'moyai': '🗿',
  'placard': '🪧', 'identification_card': '🪪',
  'atm': '🏧', 'put_litter_in_its_place': '🚮',
  'potable_water': '🚰', 'wheelchair': '♿',
  'mens': '🚹', 'womens': '🚺', 'restroom': '🚻',
  'baby_symbol': '🚼', 'wc': '🚾',
  'passport_control': '🛂', 'customs': '🛃',
  'baggage_claim': '🛄', 'left_luggage': '🛅',
  'warning': '⚠️', 'children_crossing': '🚸',
  'no_entry': '⛔', 'no_entry_sign': '🚫',
  'no_bicycles': '🚳', 'no_smoking': '🚭',
  'do_not_litter': '🚯', 'non_potable_water': '🚱',
  'no_pedestrians': '🚷', 'no_mobile_phones': '📵',
  'underage': '🔞', 'radioactive': '☢️', 'biohazard': '☣️',
  'arrow_up': '⬆️', 'arrow_upper_right': '↗️',
  'arrow_right': '➡️', 'arrow_lower_right': '↘️',
  'arrow_down': '⬇️', 'arrow_lower_left': '↙️',
  'arrow_left': '⬅️', 'arrow_upper_left': '↖️',
  'arrow_up_down': '↕️', 'left_right_arrow': '↔️',
  'leftwards_arrow_with_hook': '↩️', 'arrow_right_hook': '↪️',
  'arrow_heading_up': '⤴️', 'arrow_heading_down': '⤵️',
  'arrows_clockwise': '🔃', 'arrows_counterclockwise': '🔄',
  'back': '🔙', 'end': '🔚', 'on': '🔛', 'soon': '🔜', 'top': '🔝',
  'place_of_worship': '🛐', 'atom_symbol': '⚛️',
  'om': '🕉️', 'star_of_david': '✡️',
  'wheel_of_dharma': '☸️', 'yin_yang': '☯️',
  'latin_cross': '✝️', 'orthodox_cross': '☦️',
  'star_and_crescent': '☪️', 'peace_symbol': '☮️',
  'menorah': '🕎', 'six_pointed_star': '🔯',
  'aries': '♈', 'taurus': '♉', 'gemini': '♊', 'cancer': '♋',
  'leo': '♌', 'virgo': '♍', 'libra': '♎', 'scorpius': '♏',
  'sagittarius': '♐', 'capricorn': '♑', 'aquarius': '♒', 'pisces': '♓',
  'ophiuchus': '⛎',
  'twisted_rightwards_arrows': '🔀', 'repeat': '🔁',
  'repeat_one': '🔂', 'arrow_forward': '▶️',
  'fast_forward': '⏩', 'next_track_button': '⏭️',
  'play_or_pause_button': '⏯️', 'arrow_backward': '◀️',
  'rewind': '⏪', 'previous_track_button': '⏮️',
  'arrow_up_small': '🔼', 'arrow_double_up': '⏫',
  'arrow_down_small': '🔽', 'arrow_double_down': '⏬',
  'pause_button': '⏸️', 'stop_button': '⏹️',
  'record_button': '⏺️', 'eject_button': '⏏️',
  'cinema': '🎦', 'low_brightness': '🔅', 'high_brightness': '🔆',
  'signal_strength': '📶', 'wireless': '🛜',
  'vibration_mode': '📳', 'mobile_phone_off': '📴',
  'female_sign': '♀️', 'male_sign': '♂️', 'transgender_symbol': '⚧️',
  'heavy_multiplication_x': '✖️', 'heavy_plus_sign': '➕',
  'heavy_minus_sign': '➖', 'heavy_division_sign': '➗',
  'heavy_equals_sign': '🟰', 'infinity': '♾️',
  'bangbang': '‼️', 'interrobang': '⁉️',
  'question': '❓', 'grey_question': '❔',
  'grey_exclamation': '❕', 'exclamation': '❗', 'heavy_exclamation_mark': '❗',
  'wavy_dash': '〰️',
  'currency_exchange': '💱', 'heavy_dollar_sign': '💲',
  'medical_symbol': '⚕️', 'recycle': '♻️',
  'fleur_de_lis': '⚜️', 'trident': '🔱',
  'name_badge': '📛', 'beginner': '🔰',
  'o': '⭕', 'white_check_mark': '✅',
  'ballot_box_with_check': '☑️', 'heavy_check_mark': '✔️',
  'x': '❌', 'negative_squared_cross_mark': '❎',
  'curly_loop': '➰', 'loop': '➿',
  'part_alternation_mark': '〽️', 'eight_spoked_asterisk': '✳️',
  'eight_pointed_black_star': '✴️',
  'sparkle': '❇️', 'copyright': '©️', 'registered': '®️', 'tm': '™️',
  'hash': '#️⃣', 'asterisk': '*️⃣',
  'zero': '0️⃣', 'one': '1️⃣', 'two': '2️⃣', 'three': '3️⃣',
  'four': '4️⃣', 'five': '5️⃣', 'six': '6️⃣', 'seven': '7️⃣',
  'eight': '8️⃣', 'nine': '9️⃣', 'keycap_ten': '🔟',
  'capital_abcd': '🔠', 'abcd': '🔡', '1234': '🔢',
  'symbols': '🔣', 'abc': '🔤',
  'a': '🅰️', 'ab': '🆎', 'b': '🅱️', 'cl': '🆑',
  'cool': '🆒', 'free': '🆓',
  'information_source': '🆔',
  'id': '🆔', 'm': 'Ⓜ️', 'new': '🆕', 'ng': '🆖',
  'o2': '🅾️', 'ok': '🆗', 'parking': '🅿️',
  'sos': '🆘', 'up': '🆙', 'vs': '🆚',
  'koko': '🈁', 'sa': '🈂️',
  'ideograph_advantage': '🉐', 'accept': '🉑',
  'congratulations': '㊗️', 'secret': '㊙️',
  'u5272': '🈹', 'u5408': '🈴', 'u55b6': '🈺',
  'u6307': '🈯', 'u6708': '🈷️', 'u6709': '🈶',
  'u6e80': '🈵', 'u7121': '🈚', 'u7533': '🈸', 'u7981': '🈲', 'u7a7a': '🈳',

  // Shapes
  'red_circle': '🔴', 'orange_circle': '🟠', 'yellow_circle': '🟡',
  'green_circle': '🟢', 'large_blue_circle': '🔵',
  'purple_circle': '🟣', 'brown_circle': '🟤',
  'black_circle': '⚫', 'white_circle': '⚪',
  'red_square': '🟥', 'orange_square': '🟧', 'yellow_square': '🟨',
  'green_square': '🟩', 'blue_square': '🟦',
  'purple_square': '🟪', 'brown_square': '🟫',
  'black_large_square': '⬛', 'white_large_square': '⬜',
  'black_medium_square': '◼️', 'white_medium_square': '◻️',
  'black_medium_small_square': '◾', 'white_medium_small_square': '◽',
  'black_small_square': '▪️', 'white_small_square': '▫️',
  'large_orange_diamond': '🔶', 'large_blue_diamond': '🔷',
  'small_orange_diamond': '🔸', 'small_blue_diamond': '🔹',
  'small_red_triangle': '🔺', 'small_red_triangle_down': '🔻',
  'diamond_shape_with_a_dot_inside': '💠',
  'radio_button': '🔘', 'white_square_button': '🔳',
  'black_square_button': '🔲',

  // Flags
  'checkered_flag': '🏁', 'triangular_flag_on_post': '🚩',
  'crossed_flags': '🎌', 'black_flag': '🏴', 'white_flag': '🏳️',
  'rainbow_flag': '🏳️‍🌈', 'transgender_flag': '🏳️‍⚧️',
  'pirate_flag': '🏴‍☠️',
  'flag-ac': '🇦🇨', 'flag-ad': '🇦🇩', 'flag-ae': '🇦🇪', 'flag-af': '🇦🇫',
  'flag-ag': '🇦🇬', 'flag-ai': '🇦🇮', 'flag-al': '🇦🇱', 'flag-am': '🇦🇲',
  'flag-ao': '🇦🇴', 'flag-aq': '🇦🇶', 'flag-ar': '🇦🇷', 'flag-as': '🇦🇸',
  'flag-at': '🇦🇹', 'flag-au': '🇦🇺', 'flag-aw': '🇦🇼', 'flag-ax': '🇦🇽',
  'flag-az': '🇦🇿', 'flag-ba': '🇧🇦', 'flag-bb': '🇧🇧', 'flag-bd': '🇧🇩',
  'flag-be': '🇧🇪', 'flag-bf': '🇧🇫', 'flag-bg': '🇧🇬', 'flag-bh': '🇧🇭',
  'flag-bi': '🇧🇮', 'flag-bj': '🇧🇯', 'flag-bl': '🇧🇱', 'flag-bm': '🇧🇲',
  'flag-bn': '🇧🇳', 'flag-bo': '🇧🇴', 'flag-bq': '🇧🇶', 'flag-br': '🇧🇷',
  'flag-bs': '🇧🇸', 'flag-bt': '🇧🇹', 'flag-bv': '🇧🇻', 'flag-bw': '🇧🇼',
  'flag-by': '🇧🇾', 'flag-bz': '🇧🇿', 'flag-ca': '🇨🇦', 'flag-cc': '🇨🇨',
  'flag-cd': '🇨🇩', 'flag-cf': '🇨🇫', 'flag-cg': '🇨🇬', 'flag-ch': '🇨🇭',
  'flag-ci': '🇨🇮', 'flag-ck': '🇨🇰', 'flag-cl': '🇨🇱', 'flag-cm': '🇨🇲',
  'flag-cn': '🇨🇳', 'flag-co': '🇨🇴', 'flag-cp': '🇨🇵', 'flag-cr': '🇨🇷',
  'flag-cu': '🇨🇺', 'flag-cv': '🇨🇻', 'flag-cw': '🇨🇼', 'flag-cx': '🇨🇽',
  'flag-cy': '🇨🇾', 'flag-cz': '🇨🇿', 'flag-de': '🇩🇪', 'flag-dg': '🇩🇬',
  'flag-dj': '🇩🇯', 'flag-dk': '🇩🇰', 'flag-dm': '🇩🇲', 'flag-do': '🇩🇴',
  'flag-dz': '🇩🇿', 'flag-ea': '🇪🇦', 'flag-ec': '🇪🇨', 'flag-ee': '🇪🇪',
  'flag-eg': '🇪🇬', 'flag-eh': '🇪🇭', 'flag-er': '🇪🇷', 'flag-es': '🇪🇸',
  'flag-et': '🇪🇹', 'flag-eu': '🇪🇺', 'flag-fi': '🇫🇮', 'flag-fj': '🇫🇯',
  'flag-fk': '🇫🇰', 'flag-fm': '🇫🇲', 'flag-fo': '🇫🇴', 'flag-fr': '🇫🇷',
  'flag-ga': '🇬🇦', 'flag-gb': '🇬🇧', 'flag-gd': '🇬🇩', 'flag-ge': '🇬🇪',
  'flag-gf': '🇬🇫', 'flag-gg': '🇬🇬', 'flag-gh': '🇬🇭', 'flag-gi': '🇬🇮',
  'flag-gl': '🇬🇱', 'flag-gm': '🇬🇲', 'flag-gn': '🇬🇳', 'flag-gp': '🇬🇵',
  'flag-gq': '🇬🇶', 'flag-gr': '🇬🇷', 'flag-gs': '🇬🇸', 'flag-gt': '🇬🇹',
  'flag-gu': '🇬🇺', 'flag-gw': '🇬🇼', 'flag-gy': '🇬🇾', 'flag-hk': '🇭🇰',
  'flag-hm': '🇭🇲', 'flag-hn': '🇭🇳', 'flag-hr': '🇭🇷', 'flag-ht': '🇭🇹',
  'flag-hu': '🇭🇺', 'flag-ic': '🇮🇨', 'flag-id': '🇮🇩', 'flag-ie': '🇮🇪',
  'flag-il': '🇮🇱', 'flag-im': '🇮🇲', 'flag-in': '🇮🇳', 'flag-io': '🇮🇴',
  'flag-iq': '🇮🇶', 'flag-ir': '🇮🇷', 'flag-is': '🇮🇸', 'flag-it': '🇮🇹',
  'flag-je': '🇯🇪', 'flag-jm': '🇯🇲', 'flag-jo': '🇯🇴', 'flag-jp': '🇯🇵',
  'flag-ke': '🇰🇪', 'flag-kg': '🇰🇬', 'flag-kh': '🇰🇭', 'flag-ki': '🇰🇮',
  'flag-km': '🇰🇲', 'flag-kn': '🇰🇳', 'flag-kp': '🇰🇵', 'flag-kr': '🇰🇷',
  'flag-kw': '🇰🇼', 'flag-ky': '🇰🇾', 'flag-kz': '🇰🇿', 'flag-la': '🇱🇦',
  'flag-lb': '🇱🇧', 'flag-lc': '🇱🇨', 'flag-li': '🇱🇮', 'flag-lk': '🇱🇰',
  'flag-lr': '🇱🇷', 'flag-ls': '🇱🇸', 'flag-lt': '🇱🇹', 'flag-lu': '🇱🇺',
  'flag-lv': '🇱🇻', 'flag-ly': '🇱🇾', 'flag-ma': '🇲🇦', 'flag-mc': '🇲🇨',
  'flag-md': '🇲🇩', 'flag-me': '🇲🇪', 'flag-mf': '🇲🇫', 'flag-mg': '🇲🇬',
  'flag-mh': '🇲🇭', 'flag-mk': '🇲🇰', 'flag-ml': '🇲🇱', 'flag-mm': '🇲🇲',
  'flag-mn': '🇲🇳', 'flag-mo': '🇲🇴', 'flag-mp': '🇲🇵', 'flag-mq': '🇲🇶',
  'flag-mr': '🇲🇷', 'flag-ms': '🇲🇸', 'flag-mt': '🇲🇹', 'flag-mu': '🇲🇺',
  'flag-mv': '🇲🇻', 'flag-mw': '🇲🇼', 'flag-mx': '🇲🇽', 'flag-my': '🇲🇾',
  'flag-mz': '🇲🇿', 'flag-na': '🇳🇦', 'flag-nc': '🇳🇨', 'flag-ne': '🇳🇪',
  'flag-nf': '🇳🇫', 'flag-ng': '🇳🇬', 'flag-ni': '🇳🇮', 'flag-nl': '🇳🇱',
  'flag-no': '🇳🇴', 'flag-np': '🇳🇵', 'flag-nr': '🇳🇷', 'flag-nu': '🇳🇺',
  'flag-nz': '🇳🇿', 'flag-om': '🇴🇲', 'flag-pa': '🇵🇦', 'flag-pe': '🇵🇪',
  'flag-pf': '🇵🇫', 'flag-pg': '🇵🇬', 'flag-ph': '🇵🇭', 'flag-pk': '🇵🇰',
  'flag-pl': '🇵🇱', 'flag-pm': '🇵🇲', 'flag-pn': '🇵🇳', 'flag-pr': '🇵🇷',
  'flag-ps': '🇵🇸', 'flag-pt': '🇵🇹', 'flag-pw': '🇵🇼', 'flag-py': '🇵🇾',
  'flag-qa': '🇶🇦', 'flag-re': '🇷🇪', 'flag-ro': '🇷🇴', 'flag-rs': '🇷🇸',
  'flag-ru': '🇷🇺', 'flag-rw': '🇷🇼', 'flag-sa': '🇸🇦', 'flag-sb': '🇸🇧',
  'flag-sc': '🇸🇨', 'flag-sd': '🇸🇩', 'flag-se': '🇸🇪', 'flag-sg': '🇸🇬',
  'flag-sh': '🇸🇭', 'flag-si': '🇸🇮', 'flag-sj': '🇸🇯', 'flag-sk': '🇸🇰',
  'flag-sl': '🇸🇱', 'flag-sm': '🇸🇲', 'flag-sn': '🇸🇳', 'flag-so': '🇸🇴',
  'flag-sr': '🇸🇷', 'flag-ss': '🇸🇸', 'flag-st': '🇸🇹', 'flag-sv': '🇸🇻',
  'flag-sx': '🇸🇽', 'flag-sy': '🇸🇾', 'flag-sz': '🇸🇿', 'flag-ta': '🇹🇦',
  'flag-tc': '🇹🇨', 'flag-td': '🇹🇩', 'flag-tf': '🇹🇫', 'flag-tg': '🇹🇬',
  'flag-th': '🇹🇭', 'flag-tj': '🇹🇯', 'flag-tk': '🇹🇰', 'flag-tl': '🇹🇱',
  'flag-tm': '🇹🇲', 'flag-tn': '🇹🇳', 'flag-to': '🇹🇴', 'flag-tr': '🇹🇷',
  'flag-tt': '🇹🇹', 'flag-tv': '🇹🇻', 'flag-tw': '🇹🇼', 'flag-tz': '🇹🇿',
  'flag-ua': '🇺🇦', 'flag-ug': '🇺🇬', 'flag-um': '🇺🇲', 'flag-us': '🇺🇸',
  'flag-uy': '🇺🇾', 'flag-uz': '🇺🇿', 'flag-va': '🇻🇦', 'flag-vc': '🇻🇨',
  'flag-ve': '🇻🇪', 'flag-vg': '🇻🇬', 'flag-vi': '🇻🇮', 'flag-vn': '🇻🇳',
  'flag-vu': '🇻🇺', 'flag-wf': '🇼🇫', 'flag-ws': '🇼🇸', 'flag-xk': '🇽🇰',
  'flag-ye': '🇾🇪', 'flag-yt': '🇾🇹', 'flag-za': '🇿🇦', 'flag-zm': '🇿🇲',
  'flag-zw': '🇿🇼',

  // Miscellaneous
  'balloon': '🎈', 'pinata': '🪅',
  'confetti_ball': '🎊',
  'japanese_symbol_for_beginner': '🔰',
  'diamond_with_a_dot': '💠',
  'anchor': '⚓', 'trident': '🔱',
};

export function emojiFromName(name) {
  return EMOJI_MAP[name] || null;
}

import { Platform } from 'react-native';

export function replaceEmojisInText(text) {
  if (!text) return text;
  // BB Q20 Android has no emoji font - keep shortcodes readable
  if (Platform.OS === 'android') return text;
  return text.replace(/:([a-zA-Z0-9_+-]+):/g, function (match, name) {
    var emoji = EMOJI_MAP[name];
    return emoji || match;
  });
}

export function getTwemojiUrl(emoji) {
  try {
    if (!emoji || typeof emoji !== 'string') return null;
    var codepoints = [];
    for (var i = 0; i < emoji.length;) {
      var cp = emoji.codePointAt(i);
      if (cp === undefined) break;
      i += cp > 0xFFFF ? 2 : 1;
      if (cp !== 0xFE0F && cp !== 0xFE0E) {
        codepoints.push(cp.toString(16));
      }
    }
    if (codepoints.length === 0) return null;
    return 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/' + codepoints.join('-') + '.png';
  } catch (e) {
    return null;
  }
}

export function getTwemojiUrlByName(name) {
  var emoji = EMOJI_MAP[name];
  if (!emoji) return null;
  return getTwemojiUrl(emoji);
}
