var EMOJI_MAP = {
  '+1': '👍', '-1': '👎', 'thumbsup': '👍', 'thumbsdown': '👎',
  'heart': '❤️', 'hearts': '❤️', 'broken_heart': '💔',
  'orange_heart': '🧡', 'yellow_heart': '💛', 'green_heart': '💚',
  'blue_heart': '💙', 'purple_heart': '💜', 'black_heart': '🖤', 'white_heart': '🤍',
  'fire': '🔥', '100': '💯',
  'eyes': '👀', 'eye': '👁️',
  'smile': '😄', 'laughing': '😆', 'joy': '😂',
  'rofl': '🤣', 'rolling_on_the_floor_laughing': '🤣',
  'smiley': '😃', 'grinning': '😀', 'sweat_smile': '😅',
  'wink': '😉', 'blush': '😊', 'yum': '😋',
  'sunglasses': '😎', 'heart_eyes': '😍', 'kissing_heart': '😘',
  'thinking_face': '🤔', 'thinking': '🤔',
  'raised_hands': '🙌', 'clap': '👏', 'pray': '🙏',
  'muscle': '💪', 'ok_hand': '👌', 'wave': '👋',
  'point_up': '☝️', 'point_down': '👇', 'point_left': '👈', 'point_right': '👉',
  'white_check_mark': '✅', 'heavy_check_mark': '✔️',
  'x': '❌', 'no_entry': '⛔',
  'warning': '⚠️', 'exclamation': '❗', 'question': '❓',
  'star': '⭐', 'star2': '🌟', 'sparkles': '✨',
  'boom': '💥', 'tada': '🎉', 'party_popper': '🎉',
  'trophy': '🏆', 'medal': '🏅', 'crown': '👑',
  'rocket': '🚀', 'airplane': '✈️',
  'sunny': '☀️', 'cloud': '☁️', 'rainbow': '🌈',
  'sob': '😭', 'cry': '😢', 'angry': '😠', 'rage': '🤬',
  'scream': '😱', 'skull': '💀', 'skull_and_crossbones': '☠️',
  'poop': '💩', 'ghost': '👻', 'alien': '👽',
  'robot_face': '🤖', 'see_no_evil': '🙈', 'hear_no_evil': '🙉', 'speak_no_evil': '🙊',
  'dog': '🐶', 'cat': '🐱', 'unicorn': '🦄', 'bear': '🐻',
  'coffee': '☕', 'beer': '🍺', 'beers': '🍻', 'pizza': '🍕', 'taco': '🌮',
  'bulb': '💡', 'wrench': '🔧', 'hammer': '🔨', 'gear': '⚙️',
  'lock': '🔒', 'key': '🔑', 'zap': '⚡',
  'mega': '📣', 'bell': '🔔', 'link': '🔗',
  'heavy_plus_sign': '➕', 'heavy_minus_sign': '➖',
  'arrow_up': '⬆️', 'arrow_down': '⬇️', 'arrow_left': '⬅️', 'arrow_right': '➡️',
  'red_circle': '🔴', 'large_blue_circle': '🔵',
  'slightly_smiling_face': '🙂', 'upside_down_face': '🙃',
  'stuck_out_tongue': '😛', 'stuck_out_tongue_winking_eye': '😜',
  'memo': '📝', 'pencil': '✏️', 'calendar': '📅',
  'handshake': '🤝', 'raised_hand': '✋', 'v': '✌️',
  'fist': '✊', 'facepunch': '👊',
  'relieved': '😌', 'sleeping': '😴', 'mask': '😷',
  'nerd_face': '🤓', 'confused': '😕', 'worried': '😟',
  'disappointed': '😞', 'persevere': '😣',
  'hugging_face': '🤗', 'shushing_face': '🤫',
  'money_mouth_face': '🤑', 'exploding_head': '🤯',
  'innocent': '😇', 'smiling_imp': '😈',
  'unamused': '😒', 'rolling_eyes': '🙄', 'grimacing': '😬',
  'saluting_face': '🫡', 'melting_face': '🫠',
  'pinched_fingers': '🤌', 'crossed_fingers': '🤞',
  'call_me_hand': '🤙', 'brain': '🧠',
  'computer': '💻', 'iphone': '📱',
  'envelope': '✉️', 'email': '📧', 'package': '📦',
  'chart_with_upwards_trend': '📈', 'chart_with_downwards_trend': '📉',
  'pushpin': '📌', 'paperclip': '📎',
  'scissors': '✂️', 'wastebasket': '🗑️',
  'hourglass': '⏳', 'alarm_clock': '⏰',
  'camera': '📷', 'movie_camera': '🎥',
  'musical_note': '🎵', 'microphone': '🎤',
  'dart': '🎯', 'video_game': '🎮',
  'earth_americas': '🌎', 'earth_africa': '🌍', 'earth_asia': '🌏',
  'checkered_flag': '🏁', 'triangular_flag_on_post': '🚩',
  'no_mouth': '😶', 'neutral_face': '😐',
  'face_with_tears_of_joy': '😂',
  'smirk': '😏', 'kissing': '😗', 'kissing_closed_eyes': '😚',
  'stuck_out_tongue_closed_eyes': '😝', 'money_with_wings': '💸',
  'gem': '💎', 'ring': '💍', 'bomb': '💣',
  'pill': '💊', 'syringe': '💉',
  'ribbon': '🎀', 'gift': '🎁', 'balloon': '🎈',
  'flag-us': '🇺🇸', 'flag-eg': '🇪🇬', 'flag-sa': '🇸🇦', 'flag-gb': '🇬🇧',
};

export function emojiFromName(name) {
  return EMOJI_MAP[name] || null;
}

export function replaceEmojisInText(text) {
  if (!text) return text;
  return text.replace(/:([a-zA-Z0-9_+-]+):/g, function (match, name) {
    var emoji = EMOJI_MAP[name];
    return emoji || match;
  });
}
